(* =============================== *)
(* SmartWatchVM Language Grammar   *)
(* =============================== *)

Program   = { Line } ;

Line      = [ Label ] Statement [ Comment ] ;
Label     = Identifier ":" ;

Statement = Instr
          | Assignment
          | IfBlock
          | WhileBlock
          | Call
          | Return
          | Halt ;

Instr     = "POWERON" 
          | "POWEROFF"
          | "SHOWTIME"
          | "SETTIME" Time
          | "SETALARM" Time
          | "SETTIMER" Number
          | "NOTIFY" QuotedText
          | "SHOW" Expr
          | "HEARTBEAT"
          | "STEP"
          | "MUSICPLAY" Identifier
          | "MUSICSTOP"
          | "BLUETOOTH" ("ON" | "OFF")
          ;

Assignment = Identifier "=" Expr ;

IfBlock   = "WHEN" CondExpr "THEN" { Line } [ "ELSE" { Line } ] "ENDWHEN" ;
WhileBlock= "LOOP" CondExpr "DO" { Line } "ENDLOOP" ;

Call      = "CALL" Identifier ;
Return    = "RETURN" ;
Halt      = "HALT" ;

CondExpr  = Expr ( "==" | "!=" | "<" | "<=" | ">" | ">=" ) Expr ;

Expr      = Term { ("+"|"-") Term } ;
Term      = Factor { ("*"|"/") Factor } ;
Factor    = Number | QuotedText | Identifier | "(" Expr ")" ;

Time      = Digit Digit ":" Digit Digit ":" Digit Digit ;
Number    = Digit { Digit } ;
QuotedText= '"' { ANY - '"' } '"' ;
Identifier= Letter { Letter | Digit | "_" } ;

Comment   = ";" { ANY } ;
Digit     = "0".."9" ;
Letter    = "A".."Z" | "a".."z" ;
